services:
  gophermart-app:
    container_name: gophermart-app
    image: rusinov/gophermart-app
    command: "go run cmd/gophermart/main.go"
    depends_on:
      gophermart-db:
        condition: service_healthy
    working_dir: /app
    volumes:
      - "./:/app"
    ports:
      - "7777:7777"
    env_file:
      - .env
    build:
      dockerfile: Dockerfile

  gophermart-db:
    container_name: gophermart-db
    image: postgres:17
    command: ["postgres", "-c", "fsync=off", "-c", "synchronous_commit=off", "-c", "full_page_writes=off", "-c", "max_connections=1000"]
    volumes:
      - data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h127.0.0.1 -Ugophermart" ]
      interval: 5s
      timeout: 3s
      retries: 3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=gophermart
      - POSTGRES_USER=gophermart
      - POSTGRES_DB=gophermart
      - PGDATA=/var/lib/postgresql/data

volumes:
  data: { }
